config/routes.rb
SampleApp::Application.routes.draw do
  get "users/new"
  
  root  'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase}

	validates :name, :email, presence: true
	validates :name, length: { maximum: 50 }
	validates :email, format: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i , uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Joey Rosztoczy's Blog"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Joey Rosztoczy's Blog</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
    <div class="navbar-inner">
      <div class="container-fluid">
        <%= link_to "Joey Rosztoczy's Blog", root_path, id: "logo" %>
        <nav>
          <ul class="nav pull-right navbar-nav" style="display:inline-block">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><a href="#">Sign in</a></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all",
                                            "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container-fluid">
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>About us</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Joey Rosztoczy at
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="jumbotron">
	<h1>Welcome to my blog!</h1>

	<h2>
		This is the homepage!
	</h2>

	<%= link_to "Sign up!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>